// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amazonmini;

#nullable disable

namespace amazonmini.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811134640_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("amazonmini.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("amazonmini.OrderItems", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<decimal>("PriceDuringOrder")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("amazonmini.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "p-monitor",
                            Name = "27\" 4K Monitor",
                            Price = 329.99m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = "p-keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 119.99m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = "p-mouse",
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = "p-headset",
                            Name = "Noise-Cancelling Headset",
                            Price = 199.99m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = "p-webcam",
                            Name = "1080p Webcam",
                            Price = 69.99m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = "p-docking-station",
                            Name = "USB-C Docking Station",
                            Price = 149.99m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = "p-ssd",
                            Name = "1TB External SSD",
                            Price = 109.99m,
                            Quantity = 22
                        },
                        new
                        {
                            Id = "p-usb-hub",
                            Name = "7-in-1 USB-C Hub",
                            Price = 39.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = "p-speakers",
                            Name = "2.1 Desktop Speakers",
                            Price = 89.99m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = "p-monitor-stand",
                            Name = "Ergonomic Monitor Stand",
                            Price = 59.99m,
                            Quantity = 35
                        });
                });

            modelBuilder.Entity("amazonmini.OrderItems", b =>
                {
                    b.HasOne("amazonmini.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("amazonmini.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
